environment:
  global:
    T2D_WITHOUT_AUDIO: true
    T2D_WITHOUT_GRAPHICS: true

shallow_clone: true

image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

for:

-
  matrix:
    only:
      - platform: x86
        configuration: Debug
  build_script:
    - .ci\build_debug_x86.bat

-
  matrix:
    only:
      - platform: x64
        configuration: Debug
  build_script:
    - .ci\build_debug_x64.bat

-
  matrix:
    only:
      - platform: x86
        configuration: Release
  build_script:
    - .ci\build_release_x86.bat

-
  matrix:
    only:
      - platform: x64
        configuration: Release
  build_script:
    - .ci\build_release_x64.bat
