env:
  global:
    - T2D_WITHOUT_AUDIO=true
    - T2D_WITHOUT_GRAPHICS=true

git:
  depth: false
  quiet: true

language: cpp

jobs:
  include:

    #
    # linux (g++-7)
    #

    - os: linux
      dist: xenial
      stage: linux
      name: debug, g++-7
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7"] } }
      env: CC=gcc-7 CXX=g++-7
      script: ./.ci/build_debug.sh

    - os: linux
      dist: xenial
      stage: linux
      name: release, g++-7
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7"] } }
      env: CC=gcc-7 CXX=g++-7
      script: ./.ci/build_release.sh

    #
    # linux (g++-8)
    #

    - os: linux
      dist: xenial
      stage: linux
      name: debug, g++-8
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-8"] } }
      env: CC=gcc-8 CXX=g++-8
      script: ./.ci/build_debug.sh

    - os: linux
      dist: xenial
      stage: linux
      name: release, g++-8
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-8"] } }
      env: CC=gcc-8 CXX=g++-8
      script: ./.ci/build_release.sh

    #
    # linux (clang++-5.0)
    #

    - os: linux
      dist: xenial
      stage: linux
      name: debug, clang++-5.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7", "clang-5.0"] } }
      env: CC=clang-5.0 CXX=clang++-5.0
      script: ./.ci/build_debug.sh

    - os: linux
      dist: xenial
      stage: linux
      name: release, clang++-5.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7", "clang-5.0"] } }
      env: CC=clang-5.0 CXX=clang++-5.0
      script: ./.ci/build_release.sh

    #
    # linux (clang++-6.0)
    #

    - os: linux
      dist: xenial
      stage: linux
      name: debug, clang++-6.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7", "clang-6.0"] } }
      env: CC=clang-6.0 CXX=clang++-6.0
      script: ./.ci/build_debug.sh

    - os: linux
      dist: xenial
      stage: linux
      name: release, clang++-6.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7", "clang-6.0"] } }
      env: CC=clang-6.0 CXX=clang++-6.0
      script: ./.ci/build_release.sh

    #
    # macosx (xcode10)
    #

    - os: osx
      osx_image: xcode10
      stage: macosx
      name: debug, xcode10
      script: ./.ci/build_debug.sh

    - os: osx
      osx_image: xcode10
      stage: macosx
      name: release, xcode10
      script: ./.ci/build_release.sh

    #
    # macosx (xcode11)
    #

    - os: osx
      osx_image: xcode11
      stage: macosx
      name: debug, xcode11
      script: ./.ci/build_debug.sh

    - os: osx
      osx_image: xcode11
      stage: macosx
      name: release, xcode11
      script: ./.ci/build_release.sh
