env:
  global:
    - T2D_WITHOUT_AUDIO=true
    - T2D_WITHOUT_GRAPHICS=true

git:
  depth: false
  quiet: true

language: cpp

jobs:
  include:

    #
    # ios (xcode11)
    #

    - os: osx
      osx_image: xcode11
      stage: ios
      name: debug, xcode11
      script: .ci/builds/build_ios_simulator_debug.sh

    - os: osx
      osx_image: xcode11
      stage: ios
      name: release, xcode11
      script: .ci/builds/build_ios_simulator_release.sh

    #
    # ios (xcode12)
    #

    - os: osx
      osx_image: xcode12
      stage: ios
      name: debug, xcode12
      script: .ci/builds/build_ios_simulator_debug.sh

    - os: osx
      osx_image: xcode12
      stage: ios
      name: release, xcode12
      script: .ci/builds/build_ios_simulator_release.sh

    #
    # android (linux)
    #

    - os: linux
      dist: bionic
      stage: android
      name: debug, linux
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["ninja-build"] } }
      script: .ci/builds/build_android_debug.sh

    - os: linux
      dist: bionic
      stage: android
      name: release, linux
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["ninja-build"] } }
      script: .ci/builds/build_android_release.sh

    #
    # android (darwin)
    #

    - os: osx
      osx_image: xcode12
      stage: android
      name: debug, darwin
      script: .ci/builds/build_android_debug.sh

    - os: osx
      osx_image: xcode12
      stage: android
      name: release, darwin
      script: .ci/builds/build_android_release.sh

    #
    # emscripten (linux)
    #

    - os: linux
      dist: bionic
      stage: emscripten
      name: debug, linux
      script: .ci/builds/build_emscripten_debug.sh

    - os: linux
      dist: bionic
      stage: emscripten
      name: release, linux
      script: .ci/builds/build_emscripten_release.sh

    #
    # emscripten (darwin)
    #

    - os: osx
      osx_image: xcode12
      stage: emscripten
      name: debug, darwin
      script: .ci/builds/build_emscripten_debug.sh

    - os: osx
      osx_image: xcode12
      stage: emscripten
      name: release, darwin
      script: .ci/builds/build_emscripten_release.sh

    #
    # linux (g++-7)
    #

    - os: linux
      dist: bionic
      stage: linux
      name: debug, g++-7
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7"] } }
      env: CC=gcc-7 CXX=g++-7
      script: .ci/builds/build_linux_debug.sh

    - os: linux
      dist: bionic
      stage: linux
      name: release, g++-7
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7"] } }
      env: CC=gcc-7 CXX=g++-7
      script: .ci/builds/build_linux_release.sh

    #
    # linux (g++-8)
    #

    - os: linux
      dist: bionic
      stage: linux
      name: debug, g++-8
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-8"] } }
      env: CC=gcc-8 CXX=g++-8
      script: .ci/builds/build_linux_debug.sh

    - os: linux
      dist: bionic
      stage: linux
      name: release, g++-8
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-8"] } }
      env: CC=gcc-8 CXX=g++-8
      script: .ci/builds/build_linux_release.sh

    #
    # linux (clang++-5.0)
    #

    - os: linux
      dist: bionic
      stage: linux
      name: debug, clang++-5.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7", "clang-5.0"] } }
      env: CC=clang-5.0 CXX=clang++-5.0
      script: .ci/builds/build_linux_debug.sh

    - os: linux
      dist: bionic
      stage: linux
      name: release, clang++-5.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7", "clang-5.0"] } }
      env: CC=clang-5.0 CXX=clang++-5.0
      script: .ci/builds/build_linux_release.sh

    #
    # linux (clang++-6.0)
    #

    - os: linux
      dist: bionic
      stage: linux
      name: debug, clang++-6.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7", "clang-6.0"] } }
      env: CC=clang-6.0 CXX=clang++-6.0
      script: .ci/builds/build_linux_debug.sh

    - os: linux
      dist: bionic
      stage: linux
      name: release, clang++-6.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["libx11-dev", "libgl1-mesa-dev", "xorg-dev", "g++-7", "clang-6.0"] } }
      env: CC=clang-6.0 CXX=clang++-6.0
      script: .ci/builds/build_linux_release.sh

    #
    # darwin (xcode11)
    #

    - os: osx
      osx_image: xcode11
      stage: darwin
      name: debug, xcode11
      script: .ci/builds/build_darwin_debug.sh

    - os: osx
      osx_image: xcode11
      stage: darwin
      name: release, xcode11
      script: .ci/builds/build_darwin_release.sh

    #
    # darwin (xcode12)
    #

    - os: osx
      osx_image: xcode12
      stage: darwin
      name: debug, xcode12
      script: .ci/builds/build_darwin_debug.sh

    - os: osx
      osx_image: xcode12
      stage: darwin
      name: release, xcode12
      script: .ci/builds/build_darwin_release.sh
