set(T2D_DESKTOP_PLATFORM OFF)
set(T2D_MOBILE_PLATFORM OFF)
set(T2D_WEB_PLATFORM OFF)

if(CMAKE_SYSTEM_NAME MATCHES "Android")
    set(T2D_MOBILE_PLATFORM ON)
endif()

if(CMAKE_SYSTEM_NAME MATCHES "Darwin")
    set(T2D_DESKTOP_PLATFORM ON)
endif()

if(CMAKE_SYSTEM_NAME MATCHES "Emscripten")
    set(T2D_WEB_PLATFORM ON)
endif()

if(CMAKE_SYSTEM_NAME MATCHES "iOS")
    set(T2D_MOBILE_PLATFORM ON)
endif()

if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(T2D_DESKTOP_PLATFORM ON)
endif()

if(CMAKE_SYSTEM_NAME MATCHES "Windows")
    set(T2D_DESKTOP_PLATFORM ON)
endif()
