unset(T2D_ANDROID)
unset(T2D_DARWIN)
unset(T2D_EMSCRIPTEN)
unset(T2D_IOS)
unset(T2D_LINUX)
unset(T2D_WINDOWS)

unset(T2D_PLATFORM)

unset(T2D_DESKTOP)
unset(T2D_MOBILE)
unset(T2D_WEB)

if(CMAKE_SYSTEM_NAME MATCHES "Android")
    set(T2D_ANDROID ON)
    set(T2D_PLATFORM "mobile")
    set(T2D_MOBILE "android")
elseif(CMAKE_SYSTEM_NAME MATCHES "Darwin")
    set(T2D_DARWIN ON)
    set(T2D_PLATFORM "desktop")
    set(T2D_DESKTOP "darwin")
elseif(CMAKE_SYSTEM_NAME MATCHES "Emscripten")
    set(T2D_EMSCRIPTEN ON)
    set(T2D_PLATFORM "web")
    if(T2D_EMSCRIPTEN_ASMJS)
        unset(T2D_EMSCRIPTEN_WASM)
        set(T2D_WEB "emscripten_asmjs")
    else()
        set(T2D_EMSCRIPTEN_WASM ON)
        set(T2D_WEB "emscripten_wasm")
    endif()
elseif(CMAKE_SYSTEM_NAME MATCHES "iOS")
    set(T2D_IOS ON)
    set(T2D_PLATFORM "mobile")
    set(T2D_MOBILE "ios")
elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(T2D_LINUX ON)
    set(T2D_PLATFORM "desktop")
    set(T2D_DESKTOP "linux")
elseif(CMAKE_SYSTEM_NAME MATCHES "Windows")
    set(T2D_WINDOWS ON)
    set(T2D_PLATFORM "desktop")
    set(T2D_DESKTOP "windows")
else()
    message(SEND_ERROR "Unknown platform.")
endif()
